apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MicroserviceForAppBackstage
  description: Microservicio de citas de laboratorio, pacientes y tipos de exámenes.
  annotations:
    backstage.io/kubernetes-id: backstage2
spec:
  type: service
  owner: Yenny.Yurani.Taborda@ibm.com
  lifecycle: experimental
