name: Build and Deploy

on:
  push:
    branches:
      - main  # O el nombre de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t microservice-app-backstage:latest .

    - name: Push Docker image to Docker Hub
      run: docker push microservice-app-backstage:latest

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Apply Kubernetes resources
      run: |
        kubectl apply -f - <<EOF
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MicroserviceForAppBackstage
  description: Microservicio de citas de laboratorio, pacientes y tipos de exámenes.
spec:
  type: service
  owner: Yenny.Yurani.Taborda@ibm.com
  lifecycle: experimental
EOF
