name: Deploy Application with Namespace Creation

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# jobs:
#   deploy_application:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Install OpenShift CLI
#       run: |
#         curl -L -o oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
#         tar -xvf oc.tar.gz
#         sudo mv oc /usr/local/bin/
#         sudo chmod +x /usr/local/bin/oc

#     - name: Login to OpenShift
#       run: |
#         oc login --token=sha256~Q6MCDvTMaklTbqQo6-vW9Qmg91_Uh2fVSK7tokwKusY --server=https://c117-e.us-south.containers.cloud.ibm.com:30790

#     - name: Create Namespace
#       run: |
#         oc create namespace my-namespace

#     - name: Download ArgoCD manifests
#       run: |
#         curl -k -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjphcGlLZXkiLCJuYmYiOjE3MTY0MTA1NDgsImlhdCI6MTcxNjQxMDU0OCwianRpIjoiYXJnby10b2tlbiJ9.BoNreI3Gelmx9NjEAIWlgUdCka0Rcg8Jhio-GTkdK3A" -o bgd-app.yaml http://52.118.154.197/api/v1/applications/bdg-app

#     - name: Apply manifests with ArgoCD CLI
#       run: |
#         argocd app create bgd-app --repo https://github.com/YennyTabordaRamirez/Grupo-IA --path src/oc_infrastructure --dest-server https://c117-e.us-south.containers.cloud.ibm.com:30790 --dest-namespace my-namespace --revision master

#     - name: Sync application with ArgoCD
#       run: |
#         argocd app sync bgd-app --wait

