name: Download ArgoCD Manifests

on:
  push:
    branches:
      - master

jobs:
  download_manifests:
    runs-on: ubuntu-latest
    
    steps:
    # Paso 1: Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Instalaci贸n de la CLI de OpenShift
    - name: Install OpenShift CLI
      run: |
        curl -L -o oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
        tar -xvf oc.tar.gz
        sudo mv oc /usr/local/bin/
        sudo chmod +x /usr/local/bin/oc

    # Paso 3: Inicio de sesi贸n en OpenShift
    - name: Login to OpenShift
      run: |
        oc login --token=sha256~qkGfokc4V5tUCy7QPVWJ9yBGWLAHt3yXwa5QlYwWelE --server=https://c117-e.us-south.containers.cloud.ibm.com:30790

    # Paso 4: Descarga de los Manifestos de ArgoCD
    - name: Download ArgoCD manifests
      run: |
        curl -k -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjphcGlLZXkiLCJuYmYiOjE3MTY0MTA1NDgsImlhdCI6MTcxNjQxMDU0OCwianRpIjoiYXJnby10b2tlbiJ9.BoNreI3Gelmx9NjEAIWlgUdCka0Rcg8Jhio-GTkdK3A" -o bgd-app.yaml http://52.118.154.197/api/v1/applications/bdg-app

    # Paso 5: Verificaci贸n de la existencia del archivo
    - name: Check if file exists
      run: |
        if [ -f "bgd-app.yaml" ]; then
          echo "Archivo bgd-app.yaml encontrado."
        else
          echo "Archivo bgd-app.yaml no encontrado."
          exit 1
        fi

    # Paso 6: Visualizaci贸n de los Manifestos Descargados
    - name: Display downloaded manifests
      run: cat bgd-app.yaml
